name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - beta
env:
  PROJECT_PATH: 'src/Bulwark.Auth.Guard/Bulwark.Auth.Guard.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_PUSH_URL: 'https://api.nuget.org/v3/index.json'
  NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          working_directory: ./src
          extra_plugins: |
            @semantic-release/commit-analyzer@v9.0.2
            @semantic-release/release-notes-generator@v10.0.3
            @semantic-release/github@v8.1.0
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Pack & Publish project'
        if: ${{ steps.release.outputs.new_release_version }}
        run: |
          dotnet clean
          dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
          dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s ${{ env.NUGET_PUSH_URL }}
